# Generated by Django 4.2 on 2023-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.BooleanField(default=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('salary', models.FloatField(default=100000.345)),
                ('money', models.DecimalField(decimal_places=2, default=10.34, max_digits=4)),
                ('birthday', models.DateField(default='2000-03-04')),
                ('birthday2', models.DateTimeField(auto_now=True)),
                ('birthday3', models.DateTimeField(auto_now_add=True)),
                ('birthday4', models.DateTimeField(auto_now_add=True)),
                ('icon', models.FileField(null=True, upload_to='static/uploads')),
                ('icon2', models.ImageField(null=True, upload_to='static/uploads')),
            ],
        ),
    ]
