# Generated by Django 4.2 on 2023-05-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
    ]
